<a href="https://colab.research.google.com/github/Rohith20060521/Data-Science/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
ar1=np.array([1,2,3])
ar1
ar2=np.array([[1,2,3],[4,5,6]])
ar2
print(ar2.ndim)

In [ ]:
ar3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[0,34,54]]])
ar3
print(ar3.ndim)

In [ ]:
zeros=np.zeros((2,3))
print(zeros)

In [ ]:
ones=np.ones((2,3))
print(ones)

In [ ]:
a=np.random.random((2,3))
print(a)

In [ ]:
ide=np.eye((3))
print(ide)
print()
arange_ar=np.arange(1,10,2)
print(arange_ar)

In [ ]:
arr=np.array([[1,2,3],[4,5,8]])
print("shape: ",arr.shape)
print("size: ",arr.size)
print("Dat type: ",arr.dtype)
print("Dimensions: ",arr.ndim)

You are working as a Data Engineer for a smart agriculture startup that collects sensor data from multiple greenhouses.

Each greenhouse has sensors that record temperature (°C) readings at different times of the day.
You received the following data:
Your tasks are:
Create NumPy arrays
Create a 2D NumPy array named temp_data to represent the temperature readings from both greenhouses.
Print the array.
Check array properties
Print the shape, size, data type, and number of dimensions of temp_data.
Add a third greenhouse
The third greenhouse (GH3) records [21, 23, 22].
Create a new array updated_temp_data that includes all three greenhouses.
Generate supporting data
Create a zeros array (2×3) called sensor_error_flags to represent whether there were any sensor errors (0 means no error).
Create an identity matrix of size 3×3 named greenhouse_identity to uniquely identify each greenhouse.
Display all arrays
Print updated_temp_data, sensor_error_flags, and greenhouse_identity.


In [ ]:
temp_data=np.array([[22,25,20],[24,26,23]])
print(temp_data)
print()
print("shape: ",temp_data.shape)
print("size: ",temp_data.size)
print("Dat type: ",temp_data.dtype)
print("Dimensions: ",temp_data.ndim)
updated_temp_data=np.append(temp_data,[[21,23,22]],axis=0)
print()
sensor_error_flags=np.zeros((2,3))
greenhouse_identity=np.eye(3)
print(updated_temp_data)
print(sensor_error_flags)
print(greenhouse_identity)

In [ ]:
t1=np.array([[1,2,3],[4,5,6]])
print(t1)
print(t1[0,1])
print(t1[:,:2])

You are working as a Data Analyst at a fruit distribution company.
The company stores the number of fruit boxes shipped per day (for 1 week) in a 2D NumPy array where:
Each row represents a type of fruit.
Each column represents a day of the week (Mon–Sun).


Your Tasks
Create the 2D NumPy array
Create an array named shipments using the above data.
Access single elements (Indexing):
Get the number of Apples shipped on Wednesday.
Get the number of Oranges shipped on Sunday.
Access multiple elements (Slicing):
Extract all the weekday shipments (Mon–Fri) for all fruits.
Extract only the weekend shipments (Sat & Sun).
Extract the shipments of Apples from Wednesday to Saturday.
Bonus (Practice thinking):
Replace the Saturday shipment of Apples (currently 80) with 100 using indexing.


In [ ]:
shipments=np.array([[50,60,55,70,65,80,90],[40,45,50,60,55,70,75]])
print(shipments)
print("apples in wed: ",shipments[0,2])
print("oranges in sun: ",shipments[1,6])
print("weekday shipmentd from mon-fri: ",shipments[:,:5])
print("weekday shipments in sat,sun: ",shipments[:,5:])
shipments[0,5]=100
print("apple ship of sat to 100: ",shipments[0,5])

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print("Addition: ",a+b)
print("Multiplication: ",a*b)
print("Scalar multiply 2: ",a*2)

In [ ]:
mat1=np.array([[1,2],[3,4]])
mat2=np.array([[5,6],[7,8]])
res=np.dot(mat1,mat2)
print(mat1)
print()
print(mat2)
print()
print("dot product:",res)

1. Arithmetic ufuncs
Operate element-wise on arrays.
np.add(x, y)
np.subtract(x, y)
np.multiply(x, y)
np.divide(x, y)
np.power(x, y)
np.mod(x, y)
🔹 2. Exponential and Logarithmic ufuncs
(You already covered these)
np.exp(x)
np.log(x)
np.log10(x)
np.log2(x)
np.expm1(x)    # exp(x) - 1
🔹 3. Trigonometric ufuncs
np.sin(x)
np.cos(x)
np.tan(x)
np.arcsin(x)
np.arccos(x)
np.arctan(x)
np.degrees(x)
np.radians(x)
🔹 4. Rounding ufuncs
np.round(x)
np.floor(x)
np.ceil(x)
np.trunc(x)
🔹 5. Statistical ufuncs
(Operate along an axis or entire array)
np.min(x)
np.max(x)
np.mean(x)
np.std(x)
np.var(x)
np.sum(x)
np.prod(x)
🔹 6. Logical ufuncs
np.logical_and(x, y)
np.logical_or(x, y)
np.logical_not(x)
np.logical_xor(x, y)
🔹 7. Comparison ufuncs
(Return Boolean arrays)
np.greater(x, y)
np.less(x, y)
np.equal(x, y)
np.not_equal(x, y)
np.greater_equal(x, y)
np.less_equal(x, y)
🔹 8. Bitwise ufuncs
(Operate on integers)
np.bitwise_and(x, y)
np.bitwise_or(x, y)
np.bitwise_xor(x, y)
np.invert(x)

In [ ]:
a=np.array([1,2,3])
b=2
print(a+b) #broadcasting
print("exponent: ",np.exp(a))
print("square root: ",np.sqrt(a))
print("log: ",np.log(a))
print("sin: ",np.sin(a))
print("max: ",np.max(a))
print("compare: ",np.greater(0.1,0.9))
print("logical and: ",np.logical_and(3<4,4<5))
print("bitwise and: ",np.bitwise_and(3,4))
print("round: ",np.round(4.4))
print("sum: ",np.sum(a))
print("std: ",np.std(a))

You are a data engineer at a renewable-energy company that runs 3 solar farms.
Each farm has 4 solar panels, and each panel reports hourly energy production (kWh) for 3 hours during a test window.

Given data (raw)
Create arrays from these values:
production — shape (3 farms × 4 panels × 3 hours) represented as a 2D array per farm (you can stack/create as shown in tasks).
Farm A panels (rows = panels, cols = hours):


Tasks
Create arrays
Create three 2D NumPy arrays farmA, farmB, farmC (each shape (4,3)).
Stack them into a single 3D array production_all of shape (3, 4, 3).
Array attributes
Print the .shape, .size, .dtype, and .ndim of production_all.
Per-farm totals (arithmetic & aggregation)
Use aggregation ufuncs to compute the total energy per farm (sum across panels & hours) → total_per_farm (shape (3,)).
Compute mean, std, and var per farm.
Per-hour matrix multiplication idea (matrix op)
For a quick weighted estimate, create a hour_weights row vector of shape (3,) = [0.5, 1.0, 0.75] (weights for hour1, hour2, hour3).
Compute weighted_per_panel by performing a dot product between each farm's panel-row and hour_weights to get per-panel weighted energy. (Use np.dot / matrix multiplication appropriately.)
Broadcasting adjustments
The operator notices a fixed calibration offset of +0.5 kWh for all panels in Farm B. Use broadcasting to add this offset to Farm B data inside production_all (without recreating whole array manually).
Element-wise arithmetic (ufuncs: add/sub/mul/div/power/mod)
Compute a normalized version where you:
subtract the per-farm mean (use broadcasting),
divide by the per-farm std (broadcasting) — i.e., z-score normalize each farm's panel-hour readings.
Apply many ufuncs (use the ufuncs listed previously)
Apply the following element-wise operations (create variables for each) on the normalized data (or a copy) and show the resulting arrays (or summaries — shape/dtype/first row) where appropriate:
Exponential family: np.exp, np.expm1, np.log (note: handle non-positive inputs if needed), np.log10, np.log2.
Trigonometric: np.sin, np.cos, np.tan, np.arcsin, np.arccos, np.arctan, plus np.degrees, np.radians applied appropriately.
Rounding: np.round, np.floor, np.ceil, np.trunc.
Comparison & logical ufuncs: create a boolean mask high_output = production_all > 20 and apply np.logical_and, np.logical_or, np.logical_not, np.logical_xor combining masks (e.g., high_output and even_hours_mask). Also use comparison ufuncs like np.greater_equal, np.less.
Bitwise ufuncs (on integer arrays): create an integer array alerts = np.array([[1,0,1],[0,0,1],[1,1,0],[0,1,0]]) for each farm (shape match required) — then apply np.bitwise_and, np.bitwise_or, np.invert where sensible.
Arithmetic ufuncs again: np.add, np.subtract, np.multiply, np.divide, np.power, np.mod.
Aggregations over ufunc outputs: e.g., np.sum(np.exp(...)), np.mean(np.sin(...)).
Broadcast-based summary table
Use broadcasting to compute a (3,4) array panel_totals_per_farm = total per panel (sum across hours for each panel), and then compute a (3,) boolean needs_maintenance saying True if any panel in that farm has total < 40. Use np.min, np.max, np.any, np.all.
Final KPIs (aggregation)
Compute:
overall_total (sum of all farms),
peak_hour value (max across hours) and which farm & panel produced it (use np.argmax with careful unraveling),
average_per_panel across all farms.

In [ ]:
farmA=np.array([[10,12,11],[9,11,10],[12,13,14],[8,7,9]])
farmB=np.array([[20,19,21],[18,20,19],[22,23,21],[17,18,16]])
farmC=np.array([[15,16,14],[14,13,15],[16,17,18],[12,11,13]])
production_all=np.array([farmA,farmB,farmC])
print(production_all)
print()
print("shape: ",production_all.shape)
print("size: ",production_all.size)
print("Dat type: ",production_all.dtype)
print("Dimensions: ",production_all.ndim)
total_per_farm=np.sum(production_all,axis=(1,2))
print("total per farm: ",total_per_farm)

# Example of elements added for Farm A (production_all[0])
# Summing along axis 1 (panels) and axis 2 (hours)
# For Farm A:
# Panel 1: 10 + 12 + 11 = 33
# Panel 2: 9 + 11 + 10 = 30
# Panel 3: 12 + 13 + 14 = 39
# Panel 4: 8 + 7 + 9 = 24
# Total for Farm A: 33 + 30 + 39 + 24 = 126
# This is the first element in total_per_farm
print("mean: ",np.mean(production_all,axis=(1,2)))
print("std: ",np.std(production_all,axis=(1,2)))
print("var: ",np.var(production_all,axis=(1,2)))
hour_weights=np.array([0.5, 1.0, 0.75])
print()
print("weighted per panel: ",np.dot(production_all,hour_weights))
print("broadcasted 0.5 to b: ",production_all[1]+0.5)
farm_mean=np.mean(production_all,axis=(1,2))
farm_std=np.std(production_all,axis=(1,2))
normalized=(production_all-farm_mean)/farm_std
print("normalized: ",normalized)
print("mean_per_farm: ",farm_mean)
print("std_per_farm: ",farm_std)
print("exp: \n",np.exp(normalized))
print("expm1: \n",np.expm1(normalized))
print("log: \n",np.log(np.clip(normalized,1e-6,None)))
print("log10:\n ",np.log10(np.clip(normalized,1e-6,None)))
print("log2: \n",np.log2(np.clip(normalized,1e-6,None)))
print("sin:\n",np.sin(normalized))
print("cos:\n", np.cos(normalized))
print("tan:\n",np.tan(normalized))
print("arcsin:\n",np.arcsin(np.clip(np.sin(normalized),-1,1)))
print("arccos:\n",np.arccos(np.clip(np.cos(normalized),-1,1)))
print("arctan:\n",np.arctan(normalized))
print("degrees:\n",np.degrees(normalized))
print("radians:\n",np.radians(normalized))
print("round:\n",np.round(normalized))
print("floor:\n",np.floor(normalized))
print("ceil:\n",np.ceil(normalized))
print("trunc:\n",np.trunc(normalized))
high_output = production_all > 20
even_hours_mask=production_all%2==0
print("logival_and: ",np.logical_and(high_output,even_hours_mask))
print("logical_or: ",np.logical_or(high_output,even_hours_mask))
print("logical_not: ",np.logical_not(high_output))
print("logical_xor: ",np.logical_xor(high_output,even_hours_mask))
print("greater_equal: ",np.greater_equal(high_output,even_hours_mask))
print("less: ",np.less(high_output,even_hours_mask))
alerts = np.array([[1,0,1],[0,0,1],[1,1,0],[0,1,0]])
print("bitwise and: ",np.bitwise_and(alerts,high_output))
print("bitwise or: ",np.bitwise_or(alerts,high_output))
print("invert: ",np.invert(alerts))
print("high_output: ",high_output)
print("add: ",np.add(high_output,5))
print("subtract: ",np.subtract(high_output,5))
print("multiply: ",np.multiply(high_output,5))
print("divide: ",np.divide(high_output,5))
print("power: ",np.power(high_output,5))
print("mod: ",np.mod(high_output,5))
print("aggregate sum of np.exp: ",np.sum(np.exp(normalized)))
print("aggregate mean of np.sin: ",np.mean(np.sin(normalized)))
panel_totals_per_farm = np.sum(production_all, axis=(1, 2))
needs_maintenance = np.any(panel_totals_per_farm < 40, axis=0)
needs_maintenance1 = np.min(panel_totals_per_farm < 40, axis=0)
needs_maintenance2 = np.max(panel_totals_per_farm < 40, axis=0)
print("panel_totals_per_farm: ",panel_totals_per_farm)
print("needs_maintenance: ",needs_maintenance)
print("needs_maintenance1: ",needs_maintenance1)
print("needs_maintenance2: ",needs_maintenance2)
overall_total = production_all.sum()
peak_hour_value = np.max(production_all)
peak_farm_panel = np.unravel_index(np.argmax(production_all), production_all.shape)
average_per_panel = np.mean(production_all)
print("Overall total energy:", overall_total)
print("Peak hour value:", peak_hour_value)
print("Farm and panel with peak hour value:", peak_farm_panel)
print("Average per panel across all farms:", average_per_panel)


[[[10 12 11]
  [ 9 11 10]
  [12 13 14]
  [ 8  7  9]]

 [[20 19 21]
  [18 20 19]
  [22 23 21]
  [17 18 16]]

 [[15 16 14]
  [14 13 15]
  [16 17 18]
  [12 11 13]]]

shape:  (3, 4, 3)
size:  36
Dat type:  int64
Dimensions:  3
total per farm:  [126 234 174]
mean:  [10.5 19.5 14.5]
std:  [1.97905701 1.97905701 1.97905701]
var:  [3.91666667 3.91666667 3.91666667]

weighted per panel:  [[25.25 23.   29.5  17.75]
 [44.75 43.25 49.75 38.5 ]
 [34.   31.25 38.5  26.75]]
broadcasted 0.5 to b:  [[20.5 19.5 21.5]
 [18.5 20.5 19.5]
 [22.5 23.5 21.5]
 [17.5 18.5 16.5]]
normalized:  [[[-0.25264558 -3.78968364 -1.76851903]
  [-0.75793673 -4.2949748  -2.27381019]
  [ 0.75793673 -3.28439249 -0.25264558]
  [-1.26322788 -6.31613941 -2.77910134]]

 [[ 4.80026595 -0.25264558  3.28439249]
  [ 3.78968364  0.25264558  2.27381019]
  [ 5.81084826  1.76851903  3.28439249]
  [ 3.28439249 -0.75793673  0.75793673]]

 [[ 2.27381019 -1.76851903 -0.25264558]
  [ 1.76851903 -3.28439249  0.25264558]
  [ 2.77910134 -1.26322

In [ ]:
arr=np.array([1,2,3,4,5,6])
ar2=arr.reshape(2,3)
print(ar2)

In [ ]:
a=np.array([1,2])
b=np.array([3,4])
print("vertical stack:",np.vstack((a,b)))
print("horizontal stack:",np.hstack((a,b)))
a1=np.array([1,2,3,4,5,6])
print(np.split(a1,3))
arr=np.array([1,2,3,4,5])
print(arr[arr>3])
indice=[0,2]
print(arr[indice])

In [ ]:
arr=np.array([1,2,3])
view=arr.view()
view[0]=20
print("view:",arr) #view
copy=arr.copy()
copy[1]=23
print("copy:",arr)

In [ ]:
arr=np.array([1,2,3])
np.save('array.npy',arr)
loaded=np.load('array.npy')
print(loaded)

Create a 1D array of numbers from 10 to 50.
Create a 3x3 array of random numbers between 0 and 1.
Array Attributes
Find the shape, size, and data type of the array you created in the previous task.
Basic Operations
Add 5 to every element of a 1D array.
Multiply two 2D arrays element-wise.
Indexing and Slicing
Create a 5x5 array of integers from 1 to 25. Extract:
The first row.
The last column.
A subarray of the first three rows and first two columns.
Aggregation
Create a 10-element array of random integers between 10 and 100. Find:
The maximum value.
The minimum value.
The mean and standard deviation.
Reshaping
Convert a 1D array of numbers from 1 to 12 into a 3x4 matrix.
Broadcasting
Create a 3x3 matrix of ones. Add a 1D array [1, 2, 3] to each row.
Filtering
Create a 1D array of random integers between 1 and 50. Extract all elements that are divisible by 5.
Matrix Multiplication
Create two 2x2 matrices and perform matrix multiplication.
Advanced Indexing
Given a 4x4 array, use fancy indexing to extract the diagonal elements.

In [ ]:
arr=np.arange(10,51)
arr1=np.random.random((3,3))
print("shape: ",arr1.shape)
print("size: ",arr1.size)
print("Dat type: ",arr1.dtype)
print("Dimensions: ",arr1.ndim)
arr=arr+5
print(arr)
print()
b1=np.array([[1,2],[3,4]])
b2=np.array([[5,6],[7,8]])
print("multiplication:",b1*b2)
print()
arr=np.arange(1,26).reshape(5,5)
print(arr)
print("first row: ",arr[0])
print("last column: ",arr[:,4])
print("subarray: ",arr[:3,:2])
brr=np.random.randint(10,100,10)
print(brr)
print("min value: ",brr.min())
print("max value: ",brr.max())
print("std value: ",brr.std())
print("mean value: ",brr.mean())
crr=np.arange(1,13).reshape(3,4)
print(crr)
drr=np.ones((3,3))
print(drr)
ax=np.array([1,2,3])
drr1=drr+ax
print(drr1)
err=np.random.randint(1,51,10)
print(err[err%5==0])
print("dot product: ",np.dot(b1,b2))
arrr=np.arange(1,17).reshape(4,4)
print(arrr[[0,1,2,3],[0,1,2,3]])
print("diagonal: ",arrr.diagonal())